sm8550-common: proprietary-files: Remove libadreno_app_profiles
It depends on a module removed when we deleted QTI perfd.

error: vendor/xiaomi/sm8550-common/Android.bp:3139:1: "libadreno_app_profiles" depends on undefined module
 "vendor.qti.qspmhal@1.0".
Change-Id: I8eab2587bc231bce8c9fa0a43d4dbd87d1c2fcb2